name: DeadAnimSoldin
main: me.soldin.deadanim.DeadAnimSoldin
version: 1.0.0
api-version: 1.16
load: POSTWORLD
commands:
  deadanimsoldin:
    description: DeadAnimSoldin admin commands
    usage: /deadanimsoldin reload
    permission: deadanim.reload
permissions:
  deadanim.reload:
    description: Allow reloading the plugin config
    default: op